### ISSUE TITLE
Should dummy data for Deliverable 3 go into master or a separate release branch?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#90]
For master:
- We can also work on things like removing the "refresh" buttons

For release branch:
- Master won't be polluted by dummy data

Discuss....

**Comment by soroushMosaddad99** [comment]
In my opinion, it would be better if we created a seperate branch for the data itself, so that later on we can use them for both testing and operational purposes. In addition, it will be easier to modify them in case we changed the structure of the functions and we wanted to input the data in a different way.

**Comment by WilliamChan4** [comment]
@soroushMosaddad99 Actually, what you're describing is putting the dummy data in a test database which we can clone for testing. That's a very good idea!

However, for Deliverable 3, we'll probably need to hard code the data into the React components (since I don't think the backend including login etc. stuff will be ready by then). I was more asking whether we should hard code the data in the React components on master or on a release branch :)

**Comment by soroushMosaddad99** [comment]
oh ok sure, that makes sense. I think I'm still gonna go with the release branch anyway. Just not to make the master look dummy you know XD.

**Comment by WilliamChan4** [comment]
Sure.

**Comment by WilliamChan4** [comment]
The deliverable 3 presentation is done.
